# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cr.rpc.v1 import frame_service_pb2 as frame__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in frame_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFrame = channel.unary_unary(
                '/cr.rpc.v1.FrameService/ProcessFrame',
                request_serializer=frame__service__pb2.ProcessFrameRequest.SerializeToString,
                response_deserializer=frame__service__pb2.ProcessFrameResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/cr.rpc.v1.FrameService/Heartbeat',
                request_serializer=frame__service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=frame__service__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class FrameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFrame,
                    request_deserializer=frame__service__pb2.ProcessFrameRequest.FromString,
                    response_serializer=frame__service__pb2.ProcessFrameResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=frame__service__pb2.HeartbeatRequest.FromString,
                    response_serializer=frame__service__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cr.rpc.v1.FrameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cr.rpc.v1.FrameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cr.rpc.v1.FrameService/ProcessFrame',
            frame__service__pb2.ProcessFrameRequest.SerializeToString,
            frame__service__pb2.ProcessFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cr.rpc.v1.FrameService/Heartbeat',
            frame__service__pb2.HeartbeatRequest.SerializeToString,
            frame__service__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
